apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: frontend
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-ingress-class: "nginx"
    kubernetes.civo.com/ipv4-address: {{ .Values.ip }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domain }}
        - {{ .Values.apidomain }}
        - {{ .Values.dashboarddomain }}
      secretName: ingress-cert-data
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: {{ .Values.apidomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-svc-bridge
                port:
                  number: 80
    - host: {{ .Values.dashboarddomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-svc-bridge
                port:
                  number: 80
